import type { Book, RawBook } from '@/types/book'
import { enrich } from './gutenberg'

// A snapshot of the ~600 most-read books ships with the app (public/catalog.json,
// generated by scripts/fetch-catalog.mjs). Browsing is served from it instantly;
// the live API is only used for search, deep pagination and unknown ids.

interface CatalogFile { generatedAt: string; count: number; results: RawBook[] }

let loaded: Promise<Book[]> | null = null
let byId = new Map<number, Book>()

export function loadCatalog(): Promise<Book[]> {
  if (loaded) return loaded
  loaded = fetch('/catalog.json', { cache: 'force-cache' })
    .then((r) => (r.ok ? (r.json() as Promise<CatalogFile>) : Promise.reject(new Error('no catalog'))))
    .then((f) => {
      const books = f.results.map(enrich)
      byId = new Map(books.map((b) => [b.id, b]))
      return books
    })
    .catch(() => {
      loaded = null
      return [] as Book[]
    })
  return loaded
}

export const catalogGet = (id: number) => byId.get(id)
export const catalogReady = () => byId.size > 0

export interface LocalQuery {
  topic?: string
  authorYearStart?: number
  authorYearEnd?: number
  languages?: string
  sort?: 'popular' | 'ascending' | 'descending'
}

export function filterCatalog(books: Book[], q: LocalQuery): Book[] {
  let out = books
  if (q.languages && q.languages !== 'en') return []
  if (q.topic) {
    const re = new RegExp(q.topic.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')
    out = out.filter((b) => b.subjects.some((s) => re.test(s)) || b.bookshelves.some((s) => re.test(s)))
  }
  if (q.authorYearStart != null) out = out.filter((b) => (b.authors[0]?.birth_year ?? -9999) >= q.authorYearStart!)
  if (q.authorYearEnd != null) out = out.filter((b) => (b.authors[0]?.birth_year ?? 9999) <= q.authorYearEnd!)
  if (q.sort === 'ascending') out = [...out].sort((a, b) => a.id - b.id)
  else if (q.sort === 'descending') out = [...out].sort((a, b) => b.id - a.id)
  return out
}

export const PAGE_SIZE = 32
